spring.application.name=forohub
spring.datasource.url=jdbc:mysql://192.168.1.100:3306/prod_forohub_db?useSSL=false
spring.datasource.username=root_master_admin
spring.datasource.password=123456_super_secret

# Desactiva la sincronización para añadir un reto más
spring.jpa.hibernate.ddl-auto=none

server.error.include-stacktrace=never

api.security.secret=jrg666_hardcoded_valor